version: '2.1'

services:
  mysql:
    image: registry.cn-beijing.aliyuncs.com/k7scn/mysql:8.0-debian-10
    container_name: mysql
    ports:
      - '3306:3306'
    volumes:
      - 'mysql_data:/bitnami/mysql/data'
    environment:
      # ALLOW_EMPTY_PASSWORD yes is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      # - MYSQL_ROOT_PASSWORD=zahhi7vaefeh4she1leey1aithoh1haB
      - MYSQL_USER=goopuer
      - MYSQL_PASSWORD=zahhi7vaefeh4she1leey1aithoh1haB
      - MYSQL_DATABASE=goexample
#      - MARIADB_CHARACTER_SET=utf8mb4
    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/mysql/healthcheck.sh']
      interval: 15s
      timeout: 5s
      retries: 6
    restart: always

  adminer:
    image: registry.cn-beijing.aliyuncs.com/k7scn/adminer
    container_name: adminer
    ports:
      - '8080:8080'
    depends_on:
      - mysql
    restart: always

volumes:
  mysql_data:
    driver: local