definitions:
  health.User:
    properties:
      username:
        type: string
      userrole:
        type: string
    type: object
info:
  contact:
    email: i@ysicing.me
    name: ysicing
    url: http://github.com/ysicing
  description: This is a sample server Petstore server.
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  title: Go Example API
  version: 0.1.0
paths:
  /apis/example.dev/v1beta/db/add:
    post:
      consumes:
      - application/json
      parameters:
      - description: token
        in: header
        name: Authorization
        required: true
        type: string
      responses:
        "200":
          description: ""
      security:
      - ApiKeyAuth: []
      summary: 操作DB
      tags:
      - 示例API
  /apis/example.dev/v1beta/db/total:
    get:
      consumes:
      - application/json
      parameters:
      - description: token
        in: header
        name: Authorization
        required: true
        type: string
      responses:
        "200":
          description: ""
      security:
      - ApiKeyAuth: []
      summary: 查看DB大小
      tags:
      - 示例API
  /gentoken:
    post:
      consumes:
      - application/json
      parameters:
      - description: 用户信息
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/health.User'
      responses:
        "200":
          description: ""
      summary: 生成测试Token
      tags:
      - 默认
  /health:
    get:
      consumes:
      - pplication/json
      responses:
        "200":
          description: ""
      summary: health
      tags:
      - 默认
  /version:
    get:
      consumes:
      - application/json
      responses:
        "200":
          description: ""
      summary: version
      tags:
      - 默认
swagger: "2.0"
